### ISSUE TITLE
Wrong license? Shouldn't this library be GPL v3?

### ISSUE THREAD

**Issue by walchko** [adafruit/Adafruit_BNO055#100]
Hello, I was poking around and noticed the license on the vector, quaternion, etc files you have in the `utility` directory has this:

```
    Inertial Measurement Unit Maths Library
    Copyright (C) 2013-2014  Samuel Cowen
        www.camelsoftware.com
    Bug fixes and cleanups by Gé Vissers (gvissers@gmail.com)
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

This is GPL code ... how is this library then MIT? I would suggest ditching this code, I don't think it is really fully utilized any ways and you could just use a simple `struct` (or something) to hold the data ... JMHO

**Comment by ladyada** [comment]
thanks, if you can submit a PR for the swapped-in version that is freely licensable that would be awesome!

**Comment by walchko** [comment]
ok

**Comment by walchko** [comment]
#101 ok ... how is this?

**Comment by walchko** [comment]
oh, should I have bumped the version number in the `library.properties` file?

**Comment by supercamel** [comment]
Hello, I'm the original author of that code. It's been floating around the internet in various forms for years and I have no problem changing it to MIT or similar license.

**Comment by ladyada** [comment]
@supercamel ok would you be ok publishing the new licensed code somewhere? we'll swap it in. thank you!!!

**Comment by supercamel** [comment]
Sure, here it is

https://github.com/supercamel/imumaths

**Comment by ladyada** [comment]
@caternuson at your convenience!

**Comment by caternuson** [comment]
Done with #111 

Huge thanks to @supercamel for supporting this! :heart:
