### ISSUE TITLE
X and Z Axes Swapped?

### ISSUE THREAD

**Issue by ameliamariecollins** [adafruit/Adafruit_BNO055#103]
- Arduino board:  Mega 2560

- Arduino IDE version (found in Arduino -> About Arduino menu):  PlatformIO 5.2.0a6

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

Load the position.ino example and upload it.
Note that the position doesn't accumulate.
Print the orientation x, y, and z
Note that the X and Z axes are swapped on the gyro, but that in linearAccelData they correspond to the chip's default axes.

**Comment by ladyada** [comment]
could be! that sketch comes from a PR contribution - https://github.com/adafruit/Adafruit_BNO055/pull/46/files which means we didnt write it (or debug it)
we are pretty sure `orientation` is correct please try the bunny demo

**Comment by ameliamariecollins** [comment]
A-ha! Thank you!

(I'll close this issue.)
