### ISSUE TITLE
Euler angle range mismatch 

### ISSUE THREAD

**Issue by veeresh-dammur** [adafruit/Adafruit_BNO055#104]
Hi, 

Thanks for the wonderful repo. I have noticed that there is a mismatch in ranges of Euler angle. 
Euler x  varies from o to 360 whereas Euler y and Euler z vary -80 to +80, -180 to +180 degrees respectively. 

Is this expected behavior?

I have used [example](https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/rawdata/rawdata.ino) code to plot the Euler angles as shown below

![image](https://user-images.githubusercontent.com/77052971/122818232-3b538e80-d2d9-11eb-97eb-80874e10ad5e.png)

**Comment by ladyada** [comment]
yes it is expected
