### ISSUE TITLE
Can't use current library for multi-i2c bus.

### ISSUE THREAD

**Issue by swatkxs** [adafruit/Adafruit_BNO055#119]
I need to use four BNO055, but the current library only supports TwoWire *thewire = &Wire on default i2c bus

**Comment by caternuson** [comment]
You can pass in a different Wire instance in the constructor.
https://adafruit.github.io/Adafruit_BNO055/html/class_adafruit___b_n_o055.html#a29e00d7b95b8f7b4029b95f057ac003a

The ADR pin can be used to set an alternate address:
https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/pinouts#other-pins-2974318

For dealing with more than two BNO055's, see here for general info:
https://learn.adafruit.com/working-with-multiple-i2c-devices
