### ISSUE TITLE
Active work on adding Interrupt Support

### ISSUE THREAD

**Issue by lessonpix** [adafruit/Adafruit_BNO055#15]
Hi folks, great library (as always).  Is there any active work on adding basic interrupt support into this library?  From the datasheet, it looks like it's just a matter of writing the right code to the right registers via I2C.  I am looking to use this in a low-power project and I'd like to use the "Any Motion" interrupt to wake the MCU from a low-power state.

If not, I will take a stab at doing it myself, but I'd rather know if there's anyone on this since I can reorder my work to take advantage of it.

Thanks
Bill

**Comment by ladyada** [comment]
No active work on it, will leave this iseue open but would appreciate any PR with interrupt code

**Comment by tabchas** [comment]
Any updates on this? I might take a look on this myself.

**Comment by microbuilder** [comment]
Closing this issue, though any PRs are always welcome!
