### ISSUE TITLE
Bunny example missing Saito's OBJ Loader library

### ISSUE THREAD

**Issue by PaulStoffregen** [adafruit/Adafruit_BNO055#23]
Looks like the links on the tutorial page to Saito's OBJ Loader library are now dead.  Not possible to run the Processing code without that library.  :(

https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor?view=all#processing-test

The "Feedback" link also seems to be not working, so posting here instead.  Hope that's ok?

**Comment by microbuilder** [comment]
Thanks Paul ... I added the file to the BNO055 github repo and updated the link to point there.
