### ISSUE TITLE
Bunny example should use external crystal as well

### ISSUE THREAD

**Issue by ma-harvey** [adafruit/Adafruit_BNO055#30]
Hi, in the file "bunny.ino", in the setup() function the `bno.setExtCrystalUse(true);` line should be added after the `bno.begin()` command.

It is recommended that the BNO055 use an external crystal as the clock source whenever possible, it provides better timing accuracy than the internal RC clock

**Comment by microbuilder** [comment]
Added in https://github.com/adafruit/Adafruit_BNO055/commit/23cf3c90d807a6d483846b4bc82286b75dd37ac7
