### ISSUE TITLE
Angular Velocity Vector

### ISSUE THREAD

**Issue by show0k** [adafruit/Adafruit_BNO055#32]
In the [BN055 Adafruit product page](https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/overview), BN055 is supposed to have a "Angular Velocity Vector", but I see nothing of this in the library, nor in the documentation.
Am I missing something ?

- Arduino board:  Adafruit HUZZAH
- Arduino IDE version 1.8.1

**Comment by microbuilder** [comment]
Angular velocity is the standard gyroscope output ... gyroscopes measure angular velocity.
