### ISSUE TITLE
Euler Angles Problem

### ISSUE THREAD

**Issue by Hudemirc** [adafruit/Adafruit_BNO055#37]
Hello,

While trying the example "rawdata", it shows one of the pitch and the roll angle reverse. (For example, when the pitch angle is 5 degree, it shows -5 degree) I am not sure which one is wrong.  Could you fix that?

Huseyin

**Comment by rampageservices** [comment]
This setAxisSign PR may be relevant to you.
https://github.com/adafruit/Adafruit_BNO055/pull/38

**Comment by microbuilder** [comment]
Resolved with the latest version using #35 etc.
