### ISSUE TITLE
Changing the default configuration setting of BNO055

### ISSUE THREAD

**Issue by mrrobles09** [adafruit/Adafruit_BNO055#48]
As I was scrolling on the data sheet of BNO055 I notice that the Acc_config, Gyro_config 0, Gyro_config 1, and Mag_config were all in "read only".  If this is in read only then how will the user put their desire to set up when they need to? Also, will fusion mode overwrite the inputted set up when it is called at the end of the setup routine? See the example problem application below:

![setup](https://user-images.githubusercontent.com/32480279/37275966-81fe151c-261b-11e8-8a2c-fab9d6913a05.JPG)

![proof](https://user-images.githubusercontent.com/32480279/37275963-81580f3c-261b-11e8-919d-469735776018.JPG)

![regconfig](https://user-images.githubusercontent.com/32480279/37275964-81bb6a50-261b-11e8-843c-2a74816352a1.JPG)

![readonly](https://user-images.githubusercontent.com/32480279/37276075-c4c621a0-261b-11e8-971a-b4c7d466f536.JPG)

(The yellow highlighted part were related to the said questions)

Reference link:  www.mouser.com/ds/2/783/BST_BNO055_DS000_13-838248.pdf . Page 53, Register map Page 1.

**Comment by Tones29** [comment]
If I understand p. 20-22 of the latest manual ((https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST_BNO055_DS000_14.pdf) correctly, the workflow is as follows:
 1) The sensor starts in `CONFIGMODE`. "This is the only mode in which all the writable register map entries can be changed. (Exeptions from this rule are the interrupt registers (INT and INT_MSK) and the operation mode register (OPR_MODE), which can be modified in any operation mode.)" [p.22]
 2) The user does the configuration. According to the manual, the configuration registered mentioned above are r+w [p.78, p.79], so I guess that just the color in the table is wrong.
 3) After setting `OPR_MODE` to anything else than `CONFIGMODE`, the configuration values cannot be changed any more. Setting a fusion mode should not change these values.

**Comment by anziboy** [comment]
Hi, Im trying to change my OPR_MODE to IMU only, since I want to suspend the magnetometer, I'm wondering if you figured it out how to do it? I tried to change my OPR_MODE settings in my Adafruit library, but did not succeed. The sensors just turns off and shows no values.

Any tips? 
thank you

**Comment by caternuson** [comment]
I think this was just errata. Looks fixed in current datasheet.
![image](https://user-images.githubusercontent.com/8755041/129279515-d5dfbc06-c7fb-4408-8d7a-64a2f9cd9bd7.png)
