### ISSUE TITLE
Xbee serial communication 

### ISSUE THREAD

**Issue by kula2000uk** [adafruit/Adafruit_BNO055#51]
Hi, I am trying to get the bunny cuberotate sketch to send serial communication to send over xbee wireless serial port. My setup is an arduino uno with a SparkFun XBee Shield and a bn005 9dof board which is connected via sda too a4 and scl to a5 the xbee`s are s1 modle and am using a hobbutronics xbee usb v2 usb breakout. how do i embed the xbee library in to the processing and ide code?

**Comment by ladyada** [comment]
hiya you would use a microcontroller to read the data and send it over xbee like any other xbee data source :)
