### ISSUE TITLE
Extract IMU data whilst outputing orientation data

### ISSUE THREAD

**Issue by BenPhan19** [adafruit/Adafruit_BNO055#53]
Hi, I'm very new to all this so my question may seem basic to more senior engineer.
This fusion sensor is very capable at outputing orientation data. I wonder if it is possible to take te IMU data ( Gyro, Magneto, Acelero) for position tracking purposes? All this shoul be done without sacrifying the orienation output.

**Comment by ladyada** [comment]
position tracking - e.g. trying to fnd out where it is in a linear 3d space is a different type of problem you can use RTK or GPS for that, this library only handles rotational 3d space :)
