### ISSUE TITLE
is there need to recalibrate the complete BNO if calibration found?

### ISSUE THREAD

**Issue by shantanoo-desai** [adafruit/Adafruit_BNO055#61]
[restore_offsets.ino L214](https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/restore_offsets/restore_offsets.ino#L214)

states that when there is already calibration found the complete sensor needs to be fully recalibrated again however print statement suggests to calibrate only Magnetometer.

Is this actually a typo here? I think it should only check the magnetometer calibration status and not the complete bno status.

**Comment by hoffmannjan** [comment]
added explaining comment in code ecdc6229a57458b726f0aad1c79cfccf8a4431f1
