### ISSUE TITLE
Software issue causing the BNO to sometimes stall when powered on

### ISSUE THREAD

**Issue by Dealerpriest** [adafruit/Adafruit_BNO055#71]
As discussed in [this](https://forums.adafruit.com/viewtopic.php?f=19&t=92153&start=15#p508849) forum thread, there seems to be an issue with this library that sometimes causes the bno055 to become unresponsive on startup. Read the whole forum thread to better understand the problem.

The issue can apparently be resolved by adding a delay of about 30ms after the first call to `write8(adafruit_bno055_reg_t, byte value);`
https://github.com/adafruit/Adafruit_BNO055/blob/0a40e55d41d59cc569a2d23e9e75bfd8f12af6fc/Adafruit_BNO055.cpp#L101

**Comment by hoffmannjan** [comment]
@Dealerpriest yeah you are right, thanks, this is in master now and version bump done too
