### ISSUE TITLE
getEvent returns incorrect type for gravity data

### ISSUE THREAD

**Issue by jyganci** [adafruit/Adafruit_BNO055#76]
When playing with the read_all_data example it was noticed that adding a VECTOR_GRAVITY event in loop() and modifying the printEvent() code to process event->type==SENSOR_TYPE_GRAVITY, the displayed type was 1 (SENSOR_TYPE_ACCELEROMETER), not the expected 9 (SENSOR_TYPE_GRAVITY). Looking at the getEvent() code in the Adafruit_BNO055.cpp source, one sees
...
  else if (vec_type == Adafruit_BNO055::VECTOR_GRAVITY)
  {
    event->type = SENSOR_TYPE_ ACCELEROMETER;
    vec = getVector(Adafruit_BNO055::VECTOR_GRAVITY);

    event->acceleration.x = vec.x();
    event->acceleration.y = vec.y();
    event->acceleration.z = vec.z();
  }
...

It appears to me that the first line in the "else if" block should be

    event->type = SENSOR_TYPE_ GRAVITY;

Note that this (potential) issue is similar to issue #67 (fixed in #68).

Two attachments.
1. new_read_all_data.txt, which is your example read_all_data with additions to also print VECTOR_ACCELEROMETER, VECTOR_MAGNETOMETER, and VECTOR_GRAVITY data. (It also (correctly) prints VECTOR_LINEAR_ACCEL since the current example does not. This is fixed in a pull request (#74) that has not yet been merged into the master repository.)

2. issue_bno055_gravity.txt shows output produced by new_read_all_data, both before and after the above suggested change.

If you agree with this change, I can _try_ to generate a pull request. However, I am brand-new to github and am not sure how to officially do this. I've done the "newbie" intro to github tutorial, where one creates a repositiry with a README.md file, creates a branch, edits the README.md file, commits the changes, does a pull request, then merges it into the master. I've also created a fork of the Adafruit BNO055 master. I'm assuming that I can do something similar to the tutorial there, but am not sure if a pull request in my forked version ends up being sent to you.

Regards, John Ganci

[new_read_all_data.txt](https://github.com/adafruit/Adafruit_BNO055/files/4006254/new_read_all_data.txt)
[issue_bno055_gravity.txt](https://github.com/adafruit/Adafruit_BNO055/files/4006282/issue_bno055_gravity.txt)

**Comment by caternuson** [comment]
Fixed with #110
