### ISSUE TITLE
Accelerometer bandwidth

### ISSUE THREAD

**Issue by CherryGoose** [adafruit/Adafruit_BNO055#81]
Hello! Im currently trying to set up my bno055 to estimate its position and im looking for a way to change accelerometer bandwidth from 62.5 Hz to something like 100 Hz or 200 Hz for more accurate measurement. Can you tell me how exactly i can do that? Im interested if one can change bandwidth to later use it in fusion mode. 
P.S. Im using arduino nano to communicate with bno055.

**Comment by ladyada** [comment]
it looks like bandwidth is auto-controlled in fusion mode
![image](https://user-images.githubusercontent.com/1214161/82135617-a081aa00-97d2-11ea-87e1-9ad7fd200e81.png)

**Comment by caternuson** [comment]
Closing this in favor of #110. Can add general sensor config change requests there.
