### ISSUE TITLE
Remove _wire->begin()

### ISSUE THREAD

**Issue by kiranshila** [adafruit/Adafruit_BNO055#84]
Calling begin on a wire object in a library is bad practice as it resets the bus.

Doing so makes it imposible to use another `TwoWire` object, like one assigned for different SERCOM pins on SAMD boards as they require `pinPeripheral` to be set after `begin`, and calling `begin` again in the library resets this.

**Comment by ladyada** [comment]
hi, this is not "bad" practice, it is the standard practice for all Arduino libraries including official ones
https://github.com/arduino-libraries/Arduino_LSM6DS3/blob/master/src/LSM6DS3.cpp#L76

 if you have reproducible code you can open an issue against the SAMD repo, begin() should not change the pin allocation or usage.
thanx!

**Comment by kiranshila** [comment]
> begin() should not change the pin allocation or usage.

In fact it does https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/Wire/Wire.cpp#L37

**Comment by ladyada** [comment]
great, you can open an issue there

**Comment by kiranshila** [comment]
I'm just following your guide here https://learn.adafruit.com/using-atsamd21-sercom-to-add-more-spi-i2c-serial-ports/creating-a-new-wire
 Which clearly states that we have to call pinPeripheral immediately following `begin`. Does that then imply that this method of creating a new `TwoWire` object just doesn't work when used with libraries? If so, that's a pretty big caveat that should be mentioned.

**Comment by kiranshila** [comment]
> great, you can open an issue there

Is that actually the issue though?

**Comment by ladyada** [comment]
yes

**Comment by kiranshila** [comment]
Done
