### ISSUE TITLE
.obj file

### ISSUE THREAD

**Issue by nur921606** [adafruit/Adafruit_BNO055#98]
Hello I have question to ask. I use the cuberotate file from Adafruit BNo055 file (example_processing file) and I tried to change the bunny.obj to other object. I have the autocad 3D modelling file in .obj and .mtl I tried to change the bunny into my 3D autocad object but it written this:

Loading this = headexcavator.obj
Loading this = headexcavator.mtl
material: ‘DefaultMaterial’
Obj Name: default
and nothing appeared when I run the coding. Can somebody help me? Thank you.

**Comment by ladyada** [comment]
hi we dont support processing anymore... all that code is deprecated!
